{% set version = "0.0.2" %}

package:
  name: geojsonio
  version: {{ version }}

source:
  fn: geojsonio-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/geojsonio/geojsonio-{{ version }}.tar.gz
  sha256: c118a4c954df47c7b481458c4752c1abfcaf9803bb6340b3526b00f821a50f09

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - geojsonio = geojsonio:main


requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - github3.py
    - six

test:
  imports:
    - geojsonio
  commands:
    - geojsonio --help

about:
  home: https://github.com/jwass/geojsonio.py
  license: BSD 3-Clause
  summary: 'geojsonio CLI - Python.'

extra:
  recipe-maintainers:
    - ocefpaf
