travis:
  secure:
    BINSTAR_TOKEN: ilidoFbG2t8JSstKNhV+WC5UNQ8wCXAmYdb1LdZAYAmX2XimzjAEh7WZlXq1w8c/8RdCStYbF/1/KLgZb7vys/cTpRZv6H+S3Y6l+/fKTj97H1Vw2OBp0Nk1eIQzo7jBSEjY4EfuIWPLg0xr2wcwZyop0PtP/KNyhBd57aEd9s8FiCgQ5cSv3HH6Bk/35L+HBV6jzZyJjo8nxHOyAu9WYtseHrR3Yxb5oR0kyBar40FJOL7CYl6ghAUp4c8Vv6wtP0wzyhcvrcfn04CpiwpILqH3JLo2nDUVKTJ1vb3T5dcmo5KriXfHSFZNnz8bZgMA66rEAOD57xO+kFimfExnOLM6w4I/OjXGZ9y88VfOGWmRw/7F28BctB0psu6/w9I3zP07TM5KEhSwdPD8y2qB/tLfbRN2A03MA2BM0mDhDcBgqjolEBCYxQCw4hgr8iAVs5Syb0wMvbArVYai7kK6ht+lenjyUbm7K1BObmFMZmK52zarSSH26G2enc17vJcTmWCNxiO+gsGkwRmSZ7gy9U66MeOMG/hqXi0Vyzf1GtxOrrXVcpmG1Iv3N3a/qKqQMTeRFLVr0KIEXu0N/vvoM35WmcEFLCi2kfvWfXVPoy46KlBQ1ktqmnHEutIGaWyWupUd8IFntLsmGD68oGNAbvqQCKhzHjNf0jclQn0qPS8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
